name: 02 - Worflow Events

on: 
    pull_request:
        types: [opened]
    push:
        branches: [ main, develop ]
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch:


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                echo "I've been triggered by a(n) ${{github.event_name}} event."