name: 02 - Worflow Events

on: 
    pull_request:
        types: [opened]
    push:
        branches: [ main, develop ]
    schedule:
        - cron: '40 5,17 * * *'
    workflow_dispatch:


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                echo "Event name: ${{github.event_name}}"