name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        working-directory: 04-github-actions/react-app
        run: npm ci

      # 0 .Checkout 
      # 1. Install dependencies
      # 2. Excute automated test
