name: 05 - 1 Filters and Activity Types

on:
    pull_request:
        types: [ opened, synchronize ]
        branches:
          - main

jobs:
    Echo:
        runs-on: ubuntu-latest
        steps:
          - name: Prints Event Filters and Type of Activities
            run:
                echo "Running whenever a PR is opened or synchronized AND base branch is main"
