name: 09 - Functions

on:
    pull_request:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
          - name: Print PR title
            run: ${{ github.event.pull_request.title }}

          - name: Print PR labels
            run: echo '${{ toJson(github.event.pull_request.labels) }}'

          - name: Bug step
            if: failure() && contains(github.event.pull_request, 'fix') && cancelled() == false
            run: "I am a bug fix"

          - name: Sleep for 20 seconds
            shell: bash
            run: sleep 20

          - name: Failing step
            run: exit 1

          - name: I will be skipped
            if: success()
            run: echo "I will print if previous steps succeed."

          - name: I will execute
            if: failure()
            run: echo "I will print if previous steps fails"

          - name: I Will execute
            if: cancelled() == false
            run: echo "I will always print, except when the workflow is cancelled."

          - name: I will execute when cancelled
            if: cancelled()
            run: echo "I will always print if the steps or job be cancelled."
