name: 09 - Functions

on:
    pull_request:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
          - name: Failing step
            run: exit 0
          - name: I will be skipped
            if: success()
            run: echo "I will print if previous steps succeed."
          - name: I will execute
            if: failure()
            run: echo "I will print if previous steps fails"
          - name: I Will execute
            if: cancelled() == false
            run: echo "I will always print, except when the workflow is cancelled."
          - name: I will execute when cancelled
            if: cancelled()
            run: echo "I will always print if the steps or job be cancelled."

