name: 10 - Controlling the Execution flow

on:
    workflow_dispatch:
        inputs:
            pass-unit-test:
                type: boolean
                description: Whether until test will pas or not
                default: true

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
          - name: Lint and build
            run: |
             echo "Linting and building project"
    unit-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Running test
            run: echo "Running test"
          - name: Failing test
            if: ${{ !inputs.pass-unit-test }}
            run: exit 1
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs:
          - lint-build
          - unit-tests
        steps:
          - name: Deploying to nonprod
            run: echo "Deploying to nonprod..."
    e2e-tests:
        runs-on: ubuntu-latest
        needs:
          - deploy-nonprod
        steps:
          - name: Running e2e test
            run: echo "Running e2e test..."
    load-test:
        runs-on: ubuntu-latest
        needs:
          - deploy-nonprod
        steps:
          - name: Running load test
            run: echo "Running load test..."
    deploy-prod:
        runs-on: ubuntu-latest
        needs:
          - load-test
          - e2e-tests
        steps:
          - name: Deploying to prod
            run: echo "Deploying to prod..."
